language: go
install:
  - go get ./...
go:
  - '1.x'
os:
  - linux
matrix:
  fast_finish: true
script:
  - env GO111MODULE=on make get-tools
  - env GO111MODULE=on make test
after_success:
  - bash <(curl -s https://codecov.io/bash)
before_deploy:
  - make package
deploy:
  provider: releases
  api_key: "$GITHUB_TOKEN"
  file: "inflight-$TRAVIS_TAG.tar.gz"
  skip_cleanup: true
  on:
    tags: true
