language: go
install:
  - go get ./...
go:
  - '1.x'
os:
  - linux
matrix:
  fast_finish: true
script:
  - go test ./... -race -coverprofile=coverage.txt -covermode=atomic

after_success:
  - bash <(curl -s https://codecov.io/bash)
